<?php

// use Drupal\Core\Database\Database;

/**
 * @file
 * The main module file.
 *
 * The main module file contains hooks to create the permissions used by the
 * module, to log the data, and to expose the module to views.
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 *
 */
function i2_get_txt_data_notif_via_cronjob_cron()
{
   $_config = \Drupal::config('i2_get_txt_data_notif_via_cronjob.settings');
   $to_email = ($_config->get('admin_email_for_notif')) ? ($_config->get('admin_email_for_notif')) : ("");

   $nginx_err_log_path = '/weblog/Nginx-err.log';
   $nginx_success_log_path = '/weblog/Nginx-success.log';

   // $count_of_fail_for_notif = ($_config->get('count_of_fail_for_notif')) ? ($_config->get('count_of_fail_for_notif')) : (5);
   // 

   if ($to_email != "") {
      $site_name = \Drupal::config('system.site')->get('name');
      $checking_begin_ts = REQUEST_TIME;
      $checking_end_ts = REQUEST_TIME;

      // $checking_begin = format_date($checking_begin_ts, 'long');     // Drupal 8 outdated
      $formatter = \Drupal::service('date.formatter');
      $checking_begin = $formatter->format($checking_begin_ts, 'long');

      $email_body_details = "";
      $email_msg = "";

      $nginx_err_log_count = file_get_contents($_SERVER['DOCUMENT_ROOT'] . $nginx_err_log_path);
      $nginx_success_log_count = file_get_contents($_SERVER['DOCUMENT_ROOT'] . $nginx_success_log_path);

      $email_body_details .= "------------------------------------------------------------------------ <br>";
      $email_body_details .= "[Number of Nginx Error Yesterday] :$nginx_err_log_count <br>";
      $email_body_details .= "[Number of Nginx Success Yesterday] :$nginx_success_log_count <br>";


      // Send the email
      if ($email_body_details != "") {
         // $email_msg = json_encode($failed_user_data);
         $email_msg = "This is a flood notification, Please check the logs for more information. ";

         \Drupal::logger('i2_get_txt_data_notif_via_cronjob')->notice($email_msg);

         // Send Email Notif to site.mail
         $email_title = 'Nginx Access Count for IAAC Mainsite at ' . $checking_begin;

         $email_body_intro = 'Nginx Access Count for IAAC Mainsite <br>';
         $email_body_intro .= '================================================================== <br>';
         $email_body_intro .= 'Details of the Activity: <br>';

         $mailManager = \Drupal::service('plugin.manager.mail');
         $module = 'i2_get_txt_data_notif_via_cronjob';
         $key = 'i2_get_txt_data_notif_via_cronjob_finished';
         // $to = \Drupal::config('system.site')->get('mail');
         $to = $to_email;

         $params['email_title'] = $email_title;
         $params['email_message'] = $email_body_intro . $email_body_details;

         $langcode = \Drupal::currentUser()->getPreferredLangcode();
         $send = true;

         $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);

         if ($result['result'] !== true) {
            $message = t('There was a problem sending your message and it was not sent.');
            \Drupal::logger('i2_get_txt_data_notif_via_cronjob')->error($message);
         } else {
            $message = t('Your message has been sent.');
            \Drupal::logger('i2_get_txt_data_notif_via_cronjob')->notice($message);
         }
      }
   }
}




/**
 * Implements hook_mail()
 */
// Ref: https://www.valuebound.com/resources/blog/how-to-send-mail-programmatically-drupal-8

function i2_get_txt_data_notif_via_cronjob_mail($key, &$message, $params)
{
   $options = array(
      'langcode' => $message['langcode'],
   );

   switch ($key) {
      case 'i2_get_txt_data_notif_via_cronjob_finished':
         $message['from'] = \Drupal::config('system.site')->get('mail');
         $message['subject'] = t('@title', array('@title' => $params['email_title']), $options);
         $message['body'][] = $params['email_message'];
         break;
   }
}
